# Generated by Django 3.2.3 on 2021-05-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samochód',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('rok_produkcji', models.CharField(max_length=4)),
                ('Paliwo', models.CharField(max_length=100)),
                ('Kraj_pochodzenia', models.CharField(max_length=100)),
            ],
        ),
    ]
