# Generated by Django 3.2.3 on 2021-05-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Samochód',
            new_name='Car',
        ),
    ]
